"""add indexes on session_id and created_at

Revision ID: 5bf7fad5f5bf
Revises: b3f59a8d2c1e
Create Date: 2026-08-25 19:14:05.570623

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5bf7fad5f5bf'
down_revision: Union[str, Sequence[str], None] = 'b3f59a8d2c1e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_chat_messages_session_id', 'chat_messages', ['session_id'], unique=False)
    op.create_index('ix_chat_sessions_created_at', 'chat_sessions', ['created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_chat_sessions_created_at', table_name='chat_sessions')
    op.drop_index('ix_chat_messages_session_id', table_name='chat_messages')
    # ### end Alembic commands ###
